"""User added

Revision ID: 0c4e0b777d9c
Revises: 9178bc7380e4
Create Date: 2024-01-04 15:39:41.085153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4e0b777d9c'
down_revision = '9178bc7380e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_teams_name'), ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_teams_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teams_owner_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_teams_name'), type_='unique')
        batch_op.drop_column('owner_id')

    op.drop_table('users')
    # ### end Alembic commands ###
