"""Added JWT revoking

Revision ID: 7d68f829f772
Revises: 0c4e0b777d9c
Create Date: 2024-01-09 15:31:27.330911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d68f829f772"
down_revision = "0c4e0b777d9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
    )
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tokens_jti"), ["jti"], unique=False)

    op.alter_column("users", "name", new_column_name="username")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", new_column_name="name")

    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_jti"))

    op.drop_table("tokens")
    # ### end Alembic commands ###
